# Generated by Django 2.0.3 on 2018-04-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=20)),
                ('shou', models.CharField(max_length=50)),
                ('uadr', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=6)),
                ('tel', models.CharField(max_length=11)),
            ],
        ),
    ]
