# Generated by Django 2.0.3 on 2018-04-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='post',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='shou',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='tel',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uadr',
            field=models.CharField(default='', max_length=50),
        ),
    ]
