# Generated by Django 2.0.3 on 2018-04-03 02:39

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtitle', models.CharField(max_length=20)),
                ('gpic', models.ImageField(upload_to='daily_goods')),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_delete', models.BooleanField(default=False)),
                ('gunit', models.CharField(max_length=10)),
                ('gclick', models.IntegerField()),
                ('gdes', models.CharField(max_length=100)),
                ('gstock', models.IntegerField()),
                ('gdetail', tinymce.models.HTMLField()),
                ('grecommend', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtitle', models.CharField(max_length=20)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_goods.GoodsType'),
        ),
    ]
